### PR TITLE
chore: use node 12 (lts) and cluster 0.11

### PR DESCRIPTION
**Pull request by olizilla**
Updating the deps so ipfs-cluster-ctl can talk to cluster.ipfs.io again.

License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

### CODE REVIEW

**Comment by olizilla** [comment]
@hsanjuan updated to 0.11 ipfs-cluster-ctl, but getting this error when trying to use it against cluster.ipfs.io

```console
$ docker run \
> -v /Users/oli/Code/olizilla/best-ipfs-site:/tmp/build \
> olizilla/ipfs-dns-deploy:latest \
> ipfs-cluster-ctl \
>     --host /dnsaddr/cluster.ipfs.io \
>     --basic-auth  <redacted>\
>     add --quieter \
>     --name "ascii-ipfs" \
>     --recursive /tmp/build
An error occurred:
  Code: 0
  Message: Post libp2p://QmQCzVF95r7U9HybH37w359zBgh75Nz6v9RFAeCegBBEuc/add?chunker=size-262144&cid-version=0&hash=sha2-256&hidden=false&layout=&name=ascii-ipfs&nocopy=false&progress=false&raw-leaves=false&recursive=true&replication-max=0&replication-min=0&shard=false&shard-size=104857600&stream-channels=true&user-allocations=&wrap-with-directory=false: failed to dial : all dials failed
  * [/ip4/94.130.135.167/tcp/9097] dial tcp4 0.0.0.0:38559->94.130.135.167:9097: i/o timeout
```

**Comment by olizilla** [comment]
It fails when used from the docs site ci build too https://circleci.com/gh/ipfs/docs/627

**Comment by hsanjuan** [comment]
Yeah I suspected it was panicking on error and we could not see the actual thing... seems the peer is not responding...

**Comment by hsanjuan** [comment]
Need to bring this up with the provider as things are fine, except there is no way to get in/out of that box through its ipv4 IP.

**Pull request merged**
